In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [132]:
from sklearn.datasets import load_digits
digits = load_digits()
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [138]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3,random_state=1)


In [139]:
lr=LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

F:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9685185185185186

In [140]:
svm=SVC()
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9851851851851852

In [141]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9703703703703703

In [142]:
from sklearn.metrics import accuracy_score
y_pred = lr.predict(x_test)
acc = accuracy_score(y_pred,y_test)
acc

0.9685185185185186

In [8]:
#example of splitting
from sklearn.model_selection import KFold


In [23]:
kf = KFold(n_splits=5)
kf = kf.split([1,2,3,4,5,6,7,8,9])

In [24]:
for train_index , test_index in kf:
    print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [49]:
#function for fit and accuracy checking
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [50]:
get_score(LogisticRegression(),x_train,x_test,y_train,y_test)

F:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9165275459098498

In [36]:
#takiing real  dataset for cross validation and stratifiedFold is use bcz it will balance and adjust the train test data.
from sklearn.model_selection import StratifiedKFold
folds =  StratifiedKFold(n_splits = 3)

scores_LR=[]
scores_SVM=[]
scores_RF=[]

for train_index , test_index in folds.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
                               digits.target[train_index],digits.target[test_index]
    
    scores_LR.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    scores_RF.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))

F:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
F:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

In [37]:
scores_LR

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [39]:
scores_RF

[0.9332220367278798, 0.9532554257095158, 0.9332220367278798]

In [42]:
#same thing in one line 
from sklearn.model_selection import cross_val_score
cv=cross_val_score(LogisticRegression(),digits.data,digits.target,cv=10,scoring='accuracy')
cv

F:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
F:\Anaconda\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result

array([0.90555556, 0.96111111, 0.87777778, 0.92777778, 0.94444444,
       0.96666667, 0.95      , 0.93854749, 0.87150838, 0.93854749])

In [83]:
k=[]
for neighbor in range(50):
    if(neighbor%2!=0):
        k.append(neighbor)
print(k)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49]


In [110]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
knn = KNeighborsClassifier(n_neighbors=neighbor)
scores=[]
for neighbor in k:
    knn = KNeighborsClassifier(n_neighbors=neighbor)
    score = cross_val_score(knn,digits.data,digits.target,cv=10,scoring='accuracy')
    #knn.fit(x_train,y_train)  optional bcz cross-val also fit the data.
    scores.append(score.mean())
scores[1]

0.9766325263811299

In [108]:
scores[1]

array([0.93888889, 1.        , 0.98888889, 0.97222222, 0.96666667,
       0.97777778, 0.98333333, 0.98324022, 0.98324022, 0.97206704])

In [100]:
mse = [1-x for x in scores]
optimal_k = k[mse.index(min(mse))]
optimal_k

1